#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name :  lab423_website_update_figure_list.py
   Description :  [Add a short description here]
   Author :       Micromet
   Date :         6/1/2026 1:58 PM
   Project :      ZhihengLan
   Email: zhiheng.lan@wsu.edu
-------------------------------------------------
   Change Activity:
                   6/1/2026 - Created
-------------------------------------------------
"""
import os
import glob
from datetime import datetime

def generate_list(inputfolder,output_name):
    # Extract date from filename (assuming format YYYY-MM-DD.html)
    files = glob.glob(os.path.join(inputfolder, "*.html"))
    weekly = []
    for f in files:
        basename = os.path.basename(f)
        if basename.endswith(".html"):
            date_part = basename.replace(".html", "")
            # Validate date format, adjust if your naming is different
            try:
                date_obj = datetime.strptime(date_part, "%Y-%m-%d")
                label = date_obj.strftime("Week of %Y-%m-%d")
                # Use forward slashes for web paths
                web_path = f.replace("\\", "/")
                weekly.append(f'  {{ label: "{label}", file: "{web_path}" }}')
            except ValueError:
                print(f"Skipping {basename}: not a valid date")

    # Sort by date (newest first)
    weekly.sort(reverse=True)
    with open(output_name, "w") as out:
        out.write("// Auto-generated by generate_figures_list.py\n")
        out.write("const weeklyFigures = [\n")
        out.write(",\n".join(weekly))
        out.write("\n];\n")
    print(f"Generated {output_name} with {len(weekly)} entries.")
    return 0


# Generate JavaScript file for saving figure path and date information
folder = "figures/a3"
output = "a3_figures_list.js"
generate_list(folder,output)
folder = "figures/a5"
output = "a5_figures_list.js"
generate_list(folder,output)
folder = "figures/300a"
output = "300a_figures_list.js"
generate_list(folder,output)
